# Configuration for running tool/generate_dart_api.dart
files_to_generate:
  - core-animated-pages/core-animated-pages.html:
      # subdir imports don't work.
      omit_imports:
        - transitions/hero-transition.html
        - transitions/cross-fade.html
  - core-animated-pages/transitions/core-transition-pages.html
  - core-animated-pages/transitions/hero-transition.html
  - core-animation/core-animation.html
  - core-animation/core-animation-group.html
  - core-animation/web-animations.html
  - core-collapse/core-collapse.html
  - core-drag-drop/core-drag-drop.html
  - core-drawer-panel/core-drawer-panel.html
  - core-dropdown/core-dropdown.html
  - core-field/core-field.html
  - core-header-panel/core-header-panel.html
  - core-icon/core-icon.html
  - core-icon-button/core-icon-button.html
  - core-icons/av-icons.html
  - core-icons/communication-icons.html
  - core-icons/core-icons.html
  - core-icons/device-icons.html
  - core-icons/editor-icons.html
  - core-icons/hardware-icons.html
  - core-icons/image-icons.html
  - core-icons/maps-icons.html
  - core-icons/notification-icons.html
  - core-icons/png-icons.html
  - core-icons/social-icons.html
  - core-iconset/core-iconset.html
  - core-iconset-svg/core-iconset-svg.html
  - core-input/core-input.html
  - core-item/core-item.html
  - core-layout-grid/core-layout-grid.html
  - core-layout-trbl/core-layout-trbl.html
  - core-layout-trbl/core-slide.html
  - core-media-query/core-media-query.html:
      name_substitutions:
        query: mediaQuery
  - core-menu/core-menu.html
  - core-menu/core-submenu.html
  - core-menu-button/core-menu-button.html
  - core-meta/core-meta.html
  - core-overlay/core-key-helper.html
  - core-overlay/core-overlay.html
  - core-overlay/core-overlay-layer.html
  - core-pages/core-pages.html
  - core-popup-menu/core-popup-menu.html
  - core-popup-menu/core-popup-overlay.html
  - core-range/core-range.html
  - core-scaffold/core-scaffold.html
  - core-scroll-header-panel/core-scroll-header-panel.html
  - core-selection/core-selection.html
  - core-selector/core-selector.html
  - core-shared-lib/core-shared-lib.html
  - core-signals/core-signals.html
  - core-splitter/core-splitter.html
  - core-style/core-style.html
  - core-toolbar/core-toolbar.html
  - core-tooltip/core-tooltip.html
  - core-transition/core-transition-css.html
  - core-transition/core-transition.html
