# Configuration for running tool/generate_dart_api.dart
files_to_generate:
  - core-collapse/core-collapse.html
  - core-field/core-field.html
  - core-header-panel/core-header-panel.html
  - core-icon/core-icon.html
  - core-icon-button/core-icon-button.html
  - core-icons/core-icons.html:
      # this import has no polymer elements
      omit_imports:
        - iconsets/icons.html
  - core-iconset/core-iconset.html
  - core-iconset-svg/core-iconset-svg.html
  - core-input/core-input.html
  - core-item/core-item.html
  - core-layout-grid/core-layout-grid.html
  - core-layout-trbl/core-layout-trbl.html
  - core-layout-trbl/core-slide.html
  - core-media-query/core-media-query.html:
      name_substitutions:
        query: mediaQuery
  - core-menu/core-menu.html
  - core-menu/core-submenu.html
  - core-menu-button/core-menu-button.html
  - core-meta/core-meta.html
  - core-overlay/core-key-helper.html
  - core-overlay/core-overlay.html
  - core-overlay/core-overlay-layer.html
  - core-range/core-range.html
  - core-selection/core-selection.html
  - core-selector/core-selector.html
  - core-shared-lib/core-shared-lib.html
  - core-splitter/core-splitter.html
  - core-toolbar/core-toolbar.html
  - core-tooltip/core-tooltip.html
  - core-transition/core-transition-css.html
  - core-transition/core-transition.html
