name: core_elements
version: 0.0.4-dev.8
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer core-elements for Dart
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  polymer: ">=0.11.0+1 <0.12.0"
  quiver: ">=0.17.0 <0.19.0"
  web_components: ">=0.3.5-dev.3 <0.4.0"
dev_dependencies:
  html5lib: ">=0.11.0 <0.12.0"
  path: ">=1.0.0 <2.0.0"
  yaml: ">=1.0.0 <2.0.0"
transformers:
- polymer:
    entry_points:
    - example/core_animation.html
    - example/core_collapse.html
    - example/core_drag_drop.html
    - example/core_drawer_panel.html
    - example/core_field.html
    - example/core_header_panel.html
    - example/core_icon.html
    - example/core_icons.html
    - example/core_iconset.html
    - example/core_iconset_svg.html
    - example/core_icon_button.html
    - example/core_input.html
    - example/core_item.html
    - example/core_layout_grid.html
    - example/core_layout_trbl.html
    - example/core_list_dart.html
    - example/core_media_query.html
    - example/core_menu.html
    - example/core_menu_button.html
    - example/core_meta.html
    - example/core_overlay.html
    - example/core_pages.html
    - example/core_range.html
    - example/core_scaffold.html
    - example/core_scroll_header_panel.html
    - example/core_selection.html
    - example/core_selector.html
    - example/core_shared_lib.html
    - example/core_splitter.html
    - example/core_style.html
    - example/core_toolbar.html
    - example/core_tooltip.html
    - example/dart_ajax.html
    - example/dart_localstorage.html
    lint: false
